name: CI/CD com Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3

      - name: Build da Imagem Docker
        run: |
          docker build -t thiagoishidalbs/allbooks:latest .
          docker tag thiagoishidalbs/allbooks:latest thiagoishidalbs/allbooks:${{ github.sha }}

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

      - name: Push da Imagem Docker
        run: |
          docker push thiagoishidalbs/allbooks:latest
          docker push thiagoishidalbs/allbooks:${{ github.sha }}
